insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Road to Utopia', 6193033056956, 'Ronnie Gookes', 8);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Transcendent Man', 1697034728877, 'Selene Emilien', 11);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Living in Oblivion', 7849581734706, 'Nathanil Divis', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Batman & Robin', 8776088010868, 'Joellyn Bosward', 4);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('After the Rehearsal (Efter repetitionen)', 2845807303144, 'Tate Readmire', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Demoted', 8698904126560, 'Lauren Robertsson', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Boogie Man: The Lee Atwater Story', 8285289505822, 'Bradney Blewmen', 8);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Santo vs. las lobas', 5900951404700, 'Jo Moodie', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Premonition', 9441816732878, 'Nappy Godwin', 1);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Wooden Crosses (Les croix de bois)', 7525511408451, 'Torr Coppard', 6);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Who Is Harry Kellerman and Why Is He Saying Those Terrible Things About Me?', 9915089634195, 'Alaine Nichol', 4);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Rise of Catherine the Great, The', 2410897002616, 'Hinda Lympany', 1);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Homevideo', 7335518689019, 'Loreen Gladtbach', 2);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Turistas', 1199843944455, 'Kalindi Gatward', 7);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Something New', 7719721169697, 'Bancroft Ivory', 4);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Avengers, The', 5156869579194, 'Sebastiano Masselin', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Celtic Pride', 7032123212674, 'Frieda Hurry', 9);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Jönssonligan & den svarta diamanten', 5287038807606, 'Kelvin MacGillivrie', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Darktown Strutters (Get Down and Boogie)', 9348078052472, 'Dawn Tandey', 1);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Alter Egos', 7088660151730, 'Mikel Mines', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Lost in America', 3998650310006, 'Lorrie Drewitt', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Identification Marks: None (Rysopis) ', 9548626567853, 'Melicent Pelham', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Dumb & Dumber (Dumb and Dumber)', 4151495650101, 'Janet Rulf', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Woman on the Beach (Haebyeonui yeoin)', 3156913831009, 'Crystie Klemmt', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Harry and the Hendersons', 2243211971516, 'Cam Sennett', 11);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Twilight of the Ice Nymphs', 7715829190840, 'Wynny Polak', 2);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Mona Lisa Smile', 2080057383175, 'Frasco Priddis', 11);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Lara Croft Tomb Raider: The Cradle of Life', 6776674220280, 'Aarika Splevin', 12);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Bob & Carol & Ted & Alice', 3716231331823, 'Arie Trusler', 6);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Haywire', 4792561830048, 'Carter Shimmans', 11);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Eat Drink Man Woman (Yin shi nan nu)', 2610357716301, 'Noe Crips', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Where the Wild Things Are', 5818431690766, 'Simona Laval', 7);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Kings of Recycling (Kierrätyksen kuninkaat)', 9098875288234, 'Toddie Mirando', 13);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Graveyard of Honor (Shin jingi no hakaba)', 4329310823772, 'Kristin Cowmeadow', 10);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Vixen!', 6253670661670, 'Rock Bruntjen', 10);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Avengers Confidential: Black Widow & Punisher', 9987209947721, 'Rodrique Camelli', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('He Said, She Said', 5269017747887, 'Jay Peret', 13);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Rocky Saga: Going the Distance, The', 8173791116550, 'Robert Winfindale', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Tale of Tales (Skazka skazok)', 7283062178301, 'Jarred Mc Cahey', 7);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Shining Night: A Portrait of Composer Morten Lauridsen', 7910767048311, 'Bevon Maudett', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Land of Milk and Honey (Pays de cocagne)', 5137355479356, 'Nevsa Ivushkin', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Down and Derby', 8906539450341, 'Jephthah Pumphreys', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Return to Life', 3291265787281, 'Waylen Tippler', 13);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('633 Squadron', 6271624578825, 'Genevieve Galbreath', 2);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Private Detective 62', 8750804693535, 'Birgit Pengelly', 4);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Masquerade (Gwanghai, Wangyidoen namja)', 3012861001907, 'Vicky Cossar', 5);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('My Wife''s Relations', 9148222265283, 'Keriann Mattielli', 10);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Direct from Brooklyn', 8171599545681, 'Patrizia Schachter', 3);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Persona', 3030751152016, 'Sharia Claris', 6);
insert into LibrarySystemAPI_book (title, isbn, author, copies_available) values ('Dawn Patrol, The (Flight Commander)', 3943790043233, 'Leena Betser', 9);